name: Deploy ASP.NET Core API to Plesk

on:
  push:
    branches: ["main"]
  workflow_dispatch:   # 👈 this enables the Run workflow button

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"   # Change if you're using 6.0 or 7.0

      - name: Publish API
        run: dotnet publish -c Release -r win-x64 --self-contained true -o ./publish

      - name: Upload via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./publish/
          server-dir: /httpdocs/
